dist: xenial
env:
  global:
    - CC_TEST_REPORTER_ID=53fd579a819259bf021d8fa7081d58173595d0abf68b666c353ece33734ef636
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pipenv install -e .
  - pipenv install --dev
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install pipenv
script:
  - pytest --cov=mew tests/
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
